### PR TITLE
Three more small fixes.

### LINKED ISSUE #159: Minor Error on loading an untitled entry, `Cannot read property 'name' of undefined`
Still tracking down precisely where this error occurs. It doesn't seem to break anything, but there should be a reasonable default in place to avoid the error until an entry is given a name.

Repro:
* Open dev tools.
* Create a new entry for any schema.
* Watch your dev tools.

### LINKED ISSUE #161: Unable to close invalidMessage box.
Only happens if you...

Steps tp repro:
* Cause an invalid message to pop up. (e.g. try to Publish while a required field is empty.)
* Closes properly.
* Cause an invalid message to pop up.
* Cause an invalid message to pop up. Again.
* Unable to close invalidMessage box.

### LINKED ISSUE #162: Deleting entry should leave you on listing page.
I thought I had already opened this issue.

Deleting an entry (via the button on the listing page) should return user to the listing page once the entry has been deleted. Current behavior: Redirects user to Crucible home page, which is confusing.

### PR DESCRIPTION
**Pull request by ctcleary**
Fix invalidMessage closing. [Fixes #161]
Fix error message on creating a new entry. [Fixes #159]
Return to listing page upon deleting entry. [Fixes #162]

Bonus fix:
Move slugification to the appropriate place under `titleChange` handler.

### CODE REVIEW

File: src/pages/content-edit/name.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 "use strict";
 
 export default function name(schema, data) {
-    return data.name || "Untitled " + schema.name;
+    return data.name || schema.name && "Untitled " + schema.name || "...";
```
Comment (tivac) [inline src/pages/content-edit/name.js]: Wrap that middle condition in parens please so it's more obviously joined together.

File: src/pages/listing/index.js [hunk 2]
```diff
@@ -210,6 +210,9 @@ export function controller() {
 
         if(window.confirm("Remove " + data.name + "?")) {
             ref.remove().catch(console.error.bind(console));
+
+            // Can't figure out why `ref.remove()` was redirecting to "/"
```
Comment (tivac) [inline src/pages/listing/index.js]: Isn't there a check for validity of the current item in the details controller?

File: src/pages/content-edit/name.js (hunk 1 above)
Comment (ctcleary) [inline src/pages/content-edit/name.js]: Sure thing. I actually went back and forth on doing that, heh.

File: src/pages/listing/index.js (hunk 2 above)
Comment (ctcleary) [inline src/pages/listing/index.js]: Trying to track this one down again before we merge a band aid, but not having a ton of luck yet. (I originally threw my hands up and gave up because I figured it was something weird in either firebase or mithril that I didn't want to go spelunking for.)

Comment (tivac) [inline src/pages/listing/index.js]: https://github.com/tivac/crucible/blob/master/src/pages/content-edit/index.js#L55-L57 ? 

Remember that `firebase.on` will fire any time any updates occur to the item, which could definitely include deletion.

Comment (ctcleary) [inline src/pages/listing/index.js]: Okay. First up, you're right. That is exactly where the problem was. 

But it didn't occur to me, because I didn't think that event listener would be listening while I was on the listing page. I wasn't even thinking about stuff in `content-edit/`. But I just ran a quick test, and proved it out. The behavior only occurs if you've been to a `content-edit` page and haven't refreshed since then.

As a best practice, it looks like we should be calling `ref.off()` before we set up any `listing` or `content-edit` pages. Another quick test showed me that going from listing->entry 4 times adds 4 separate instances of every `ref.on("value", callback);` listener, so we're hamstringing our performance and doing a lot of extra rapidfire work.

**Comment by tivac** [comment]
:+1:
